baseURL = "http://hambaobao.me/"
languageCode = "en-us"
title = "Home"
theme = "PaperMod"

[params]
author = "Lei Zhang"
description = "This is my personal website."

homeInfoParams = { Title = "👋 Hi, I'm Lei Zhang", Content = "Welcome to my personal site." }

ShowShareButtons = false
ShowReadingTime = true
ShowCodeCopyButtons = true
customCSS = ["css/override.css"]

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "publications"
name = "Publications"
url = "/publications/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3
